#!/usr/bin/env node
'use strict';

const CONFIG = 'ng-swagger-gen.json';
const fs = require('fs')
const path = require('path')

var options = null;
if (process.argv.length < 3) {
  // No arguments - check if the ng-swagger-gen.json file exists
  if (fs.existsSync(CONFIG)) {
    // It exists, read options from it
    options = JSON.parse(fs.readFileSync(CONFIG, "utf8"));
  } else {
    // The config file doesn't exist. Log and exit.
    console.log("No file " + CONFIG + " in current directory. It means the "
      + "swagger file location is required. Usage: \n" + process.argv[1] 
      + " <swagger.json> [output dir]");
    process.exit(1);
  }
} else {
  // Arguments were given. Prepare the options from it
  options = {
    swagger: process.argv[2],
    output: process.argv.length > 3 ? process.argv[3] : 'src/app/api'
  }
}

var ngSwaggerGen = require("./ng-swagger-gen.js");
ngSwaggerGen(options);
